"""PDF report generator for NextCare screening results."""

from datetime import datetime

from fpdf import FPDF


def _risk_label(score: float | None) -> str:
    if score is None:
        return "N/A"
    if score < 0.3:
        return "Low Risk"
    if score < 0.7:
        return "Moderate"
    return "Elevated"


def _score_str(score: float | None) -> str:
    if score is None:
        return "N/A"
    return f"{round(score * 100)}/100"


def generate_report_pdf(
    acoustic_result: float | None,
    semantic_result: float | None,
    fusion_result: float | None,
    report_text: str | None,
    subject_id: str = "anonymous",
) -> bytes:
    """Generate a PDF screening report and return it as bytes."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()

    # --- Header ---
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(0, 12, "NextCare Screening Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(120, 120, 120)
    now = datetime.now()
    pdf.cell(
        0, 8,
        f"Date: {now.strftime('%Y-%m-%d')}    Time: {now.strftime('%H:%M:%S')}",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.cell(0, 6, f"Subject: {subject_id}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(8)

    # --- Scores Table ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Assessment Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    col_widths = [70, 35, 40]
    headers = ["Metric", "Score", "Risk Level"]

    pdf.set_font("Helvetica", "B", 10)
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 8, h, border=1)
    pdf.ln()

    pdf.set_font("Helvetica", "", 10)
    rows = [
        ("Vocal Frailty (Acoustic)", acoustic_result),
        ("Cognitive Footprint (Semantic)", semantic_result),
        ("Combined Score", fusion_result),
    ]
    for label, score in rows:
        pdf.cell(col_widths[0], 8, label, border=1)
        pdf.cell(col_widths[1], 8, _score_str(score), border=1)
        pdf.cell(col_widths[2], 8, _risk_label(score), border=1)
        pdf.ln()

    pdf.ln(10)

    # --- Report Body ---
    if report_text:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Detailed Report", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        # Replace common unicode characters that Helvetica can't render
        safe_text = (
            report_text
            .replace("\u2019", "'")
            .replace("\u2018", "'")
            .replace("\u201c", '"')
            .replace("\u201d", '"')
            .replace("\u2014", "-")
            .replace("\u2013", "-")
            .replace("\u2026", "...")
            .replace("\u2022", "-")
        )
        pdf.multi_cell(0, 6, safe_text)

    # --- Disclaimer ---
    pdf.ln(10)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 170, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(
        0, 5,
        "Disclaimer: This report is generated by an automated screening tool and does not "
        "constitute a medical diagnosis. Please consult a qualified healthcare professional "
        "for clinical evaluation and diagnosis.",
    )

    return bytes(pdf.output())
