"""NextCare — Dementia Screening Tool (Streamlit UI).

Two-tab interface:
  Tab 1: Upload audio file + configure screening
  Tab 2: View screening report with scores

Currently uses mock data. See PIPELINE INTEGRATION POINT below
for wiring to the real LangGraph pipeline.
"""

import time
import streamlit as st

# =====================================================================
# Page config
# =====================================================================

st.set_page_config(
    page_title="NextCare | Dementia Screening",
    page_icon="🧠",
    layout="centered",
)

# =====================================================================
# Mock data (replace with real pipeline once fusion_agent is done)
# =====================================================================

MOCK_RESULT = {
    "acoustic_result": 0.28,
    "semantic_result": 0.35,
    "fusion_result": 0.31,
    "report": (
        "## Screening Summary\n\n"
        "Based on the voice-based screening, the individual's speech patterns "
        "fall within the **low-risk range** for cognitive decline indicators. "
        "The combined screening score of 0.31 suggests that current speech "
        "characteristics are largely consistent with typical patterns.\n\n"
        "## Vocal Analysis Findings\n\n"
        "The Vocal Frailty Score (0.28) indicates that acoustic features — "
        "including speech rhythm, pitch variability, and vocal quality — are "
        "within normal ranges. No significant markers of vocal deterioration "
        "were detected in this recording.\n\n"
        "## Language & Cognitive Findings\n\n"
        "The Cognitive Footprint Score (0.35) reflects a mild presence of "
        "linguistic patterns sometimes associated with early cognitive changes. "
        "These include occasional word-finding pauses and moderate use of "
        "filler words. However, overall sentence complexity, vocabulary range, "
        "and discourse coherence remain within expected levels.\n\n"
        "## Key Observations\n\n"
        "- Speech rhythm and vocal quality are within normal parameters\n"
        "- Occasional hesitation patterns observed but within typical range\n"
        "- Vocabulary diversity (MATTR) is adequate\n"
        "- Discourse coherence is maintained throughout the recording\n\n"
        "## Recommendations\n\n"
        "- The current screening results do not indicate an urgent need for "
        "clinical evaluation, but periodic screening (every 6-12 months) is "
        "recommended as a preventive measure.\n"
        "- Maintaining an active social life, regular physical exercise, and "
        "cognitively stimulating activities can support long-term cognitive health.\n"
        "- If you notice any changes in memory, language, or daily functioning, "
        "consider consulting a geriatrician or visiting a memory clinic.\n\n"
        "## Disclaimer\n\n"
        "> **Important Disclaimer:** This report is generated by an automated "
        "screening tool and does NOT constitute a medical diagnosis. Dementia "
        "can only be diagnosed by a qualified healthcare professional through "
        "comprehensive clinical assessment. This screening is intended to "
        "identify individuals who may benefit from further evaluation. Please "
        "consult a doctor or specialist for a formal assessment."
    ),
    "messages": ["[mock] Using demo data — pipeline not connected yet"],
}


# === PIPELINE INTEGRATION POINT ===
# Once fusion_agent is implemented, replace the mock data block above
# and the _run_mock_pipeline() function below with:
#
#   from agents.graph import build_graph
#
#   @st.cache_resource
#   def _get_pipeline():
#       return build_graph()
#
#   def _run_pipeline(audio_path, subject_id, language_code, file_name):
#       pipeline = _get_pipeline()
#       result = pipeline.invoke({
#           "audio_file_path": audio_path,
#           "subject_id": subject_id,
#           "report_language": language_code,
#           "file_name": file_name,
#       })
#       return result
#
# The result dict contains the same keys used in MOCK_RESULT:
#   - acoustic_result (float): Vocal Frailty Score (0-1)
#   - semantic_result (float): Cognitive Footprint Score (0-1)
#   - fusion_result   (float): Combined Screening Score (0-1)
#   - report          (str):   LLM-generated caregiver report (markdown)
#   - messages        (list):  Pipeline log messages
#
# After wiring, delete MOCK_RESULT and _run_mock_pipeline().
# ===================================


def _run_mock_pipeline(progress_callback=None):
    """Simulate pipeline execution with progress updates."""
    steps = [
        ("Loading audio file...", 0.10),
        ("Chunking audio into 2-second segments...", 0.20),
        ("Extracting acoustic embeddings (HeAR)...", 0.35),
        ("Transcribing speech (MERaLiON)...", 0.50),
        ("Classifying vocal patterns...", 0.60),
        ("Extracting linguistic features...", 0.70),
        ("Classifying cognitive patterns...", 0.80),
        ("Fusing branch scores...", 0.90),
        ("Generating screening report...", 0.95),
        ("Complete!", 1.00),
    ]
    for label, progress in steps:
        if progress_callback:
            progress_callback(progress, label)
        time.sleep(0.4)
    return MOCK_RESULT


# =====================================================================
# Helpers
# =====================================================================

LANGUAGES = {
    "English": "en",
    "Mandarin (中文)": "zh",
}


def _score_color(score):
    """Return colour label based on score threshold."""
    if score < 0.3:
        return "green", "Low Risk"
    elif score < 0.7:
        return "orange", "Moderate"
    else:
        return "red", "Elevated"


def _render_score_bar(label, score, help_text=""):
    """Render a score with a coloured progress bar."""
    color, risk_label = _score_color(score)

    color_map = {"green": "#28a745", "orange": "#ffc107", "red": "#dc3545"}
    bar_color = color_map[color]

    st.markdown(
        f"**{label}**"
        f'<span style="float:right; color:{bar_color}; font-weight:600;">'
        f"{risk_label} ({score:.2f})</span>",
        unsafe_allow_html=True,
    )
    st.progress(score)
    if help_text:
        st.caption(help_text)


# =====================================================================
# Session state initialisation
# =====================================================================

if "results" not in st.session_state:
    st.session_state.results = None
if "uploaded_file_name" not in st.session_state:
    st.session_state.uploaded_file_name = None


# =====================================================================
# Header
# =====================================================================

st.markdown(
    "<h1 style='text-align:center;'>Dementia Screening Tool</h1>"
    "<p style='text-align:center; color:grey;'>"
    "A calm, voice-based assessment designed to help you monitor "
    "cognitive health from the comfort of your home."
    "</p>",
    unsafe_allow_html=True,
)

st.divider()

# =====================================================================
# Tabs
# =====================================================================

tab_upload, tab_report = st.tabs(["Upload Audio", "Screening Report"])

# ----- Tab 1: Upload -----
with tab_upload:
    st.subheader("Step 1: Voice Recording Upload")
    st.write(
        "Upload a WAV audio recording of natural speech. "
        "The recording should ideally be 30 seconds or longer."
    )

    uploaded_file = st.file_uploader(
        "Choose an audio file",
        type=["wav"],
        help="Supported format: WAV (16-bit PCM). Mono or stereo.",
    )

    col1, col2 = st.columns(2)
    with col1:
        language = st.selectbox("Report language", list(LANGUAGES.keys()))
    with col2:
        subject_id = st.text_input("Subject ID (optional)", value="anonymous")

    # Show audio player if file uploaded
    if uploaded_file is not None:
        st.audio(uploaded_file, format="audio/wav")

    # Run button
    run_clicked = st.button(
        "Run Screening",
        type="primary",
        disabled=(uploaded_file is None),
        use_container_width=True,
    )

    if run_clicked and uploaded_file is not None:
        # Check if we already have results for this exact file
        if st.session_state.uploaded_file_name == uploaded_file.name:
            st.info("Results already available — switch to the **Screening Report** tab.")
        else:
            # Run pipeline with progress
            progress_bar = st.progress(0, text="Starting analysis...")

            def update_progress(value, text):
                progress_bar.progress(value, text=text)

            result = _run_mock_pipeline(progress_callback=update_progress)

            # Store in session state
            st.session_state.results = result
            st.session_state.uploaded_file_name = uploaded_file.name

            progress_bar.progress(1.0, text="Analysis complete!")
            st.success(
                "Screening complete! Switch to the **Screening Report** tab to view results."
            )

    # New screening button (only shown if results exist)
    if st.session_state.results is not None:
        if st.button("Clear & Start New Screening"):
            st.session_state.results = None
            st.session_state.uploaded_file_name = None
            st.rerun()


# ----- Tab 2: Report -----
with tab_report:
    if st.session_state.results is None:
        st.info("Please upload an audio file and run the screening first.")
    else:
        result = st.session_state.results

        st.subheader("Initial Findings")

        # Score bars
        col_scores, col_summary = st.columns([1, 1])

        with col_scores:
            _render_score_bar(
                "Cognitive Stability",
                result["acoustic_result"],
                help_text="Based on vocal patterns (rhythm, pitch, quality)",
            )
            st.markdown("")
            _render_score_bar(
                "Speech Fluency",
                result["semantic_result"],
                help_text="Based on language patterns (word choice, coherence)",
            )
            st.markdown("")
            _render_score_bar(
                "Combined Screening Score",
                result["fusion_result"],
                help_text="Weighted fusion of both assessments",
            )

        with col_summary:
            st.markdown("**Summary**")
            # Extract first paragraph of report as quick summary
            report_text = result.get("report", "")
            paragraphs = [p.strip() for p in report_text.split("\n\n") if p.strip()]
            # Find first non-heading paragraph
            for p in paragraphs:
                if not p.startswith("#"):
                    st.write(p)
                    break

        st.divider()

        # Full report
        st.subheader("Full Screening Report")
        st.markdown(result.get("report", "*No report available.*"))

        # Pipeline log (collapsible)
        with st.expander("Pipeline Log"):
            for msg in result.get("messages", []):
                st.text(msg)

# =====================================================================
# Footer disclaimer
# =====================================================================

st.divider()
st.caption(
    "NextCare is a screening tool, not a diagnostic medical device. "
    "Always consult with your doctor for medical advice."
)
